### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by hazendaz** [comment]
@velo awesome to see you joining back on this project.  Now the effort will be to make these mergable.  I believe there is some overlap in some areas.  To some degree I looked to you for various changes to help get this going on newer maven style last year.  I invisioned you bringing this back into the fold. The only concern I had at that time was the overal level of changes.  But I think with a little hard work we can get these back together and start moving forward.  Now that this is under revelc project and original author support, I see us moving fast to the future.

Now seeing this PR, how do you want to start this?  Maybe cherry pick things for a bit until we can figure out the major differences?

**Comment by ctubbsii** [comment]
@hazendaz : I sent an email to @velo to invite him to join us and merge these back together, based on your comments on #27 . Even if his changes don't achieve the XML formatting mentioned there, I think it's still a reasonable thing to bring these back into sync and consolidate the feature set.

Some work will be needed, of course, to see where the changes are, and what else needs to be done before these can be merged. I haven't really dived in yet to the changes, but if there's something I can help with, let me know.

**Comment by velo** [comment]
@hazendaz well, there are at least 3 major differences between my project and the original one.
1 - Support to java and javascript formatter (could go for xml, html, actionscript, whatever)
2 - m2Eclipse configurator... so the same configuration used on maven plugin is gonna be applied to the IDE
3 - I get jdt-core from eclipse p2 repositories, this allows me to grab the latest version each build....

the problem is that I relocate every package and groupId, so that is gonna make troubles on merge

**Comment by velo** [comment]
@ctubbsii for sure, more work is needed, this is just a initial merge with the major conflicts being solved...

**Pull request closed without merging**
