### PR TITLE
[mvn] Change the name from 'ossrh' to 'sonatype-nexus-snapshots' (leg…

### PR DESCRIPTION
**Pull request by hazendaz**
…acy usage here)

### CODE REVIEW

**Comment by ctubbsii** [comment]
@hazendaz Can you help me understand what this is for? Is this for automatic deployment of snapshots to OSSRH? Do we really need that? With all the changes happening migrating people away from OSSRH, isn't this going to make it more difficult for revelc org to move away from OSSRH to the new Maven Central? I don't think we need snapshots automatically uploaded. We can deploy them any time if we need to.

Also, why the old name here?

Also, the credentials should be per-user. Are you using your own personal credentials stored in the repo as secrets for GitHub Actions? I would strongly advise against doing that. Others with write access to this repo can create a GitHub Action to reveal your personal credentials, and that breaks the security principle of nonrepudiation.

**Comment by hazendaz** [comment]
Last I had looked ossrh was still the suggestion and had nothing to do with the new maven central site.  In fact ossrh had nothing do do with sonatype either.  If you have some definitive site that states otherwise that would be great to see as I'll change too but I did specifically look at this time.

The credentials are not user / password.  Its user which is encrypted as well as token which is encrypted.  Even if someone broke my token, they would not have my password and I'm not aware of any way to print out that data given how it is handled.  If that were the case, credentials in github shouldn't exist at all.  That stuff shows up as *** when printed, I'm not aware of any current defects to break that and I can reject the token at any time if hacked.  Do you have a specific case in might where that is currently possible?

**Comment by ctubbsii** [comment]
> Last I had looked ossrh was still the suggestion and had nothing to do with the new maven central site.

I'm not sure what you mean by this.

> In fact ossrh had nothing do do with sonatype either.

OSSRH is run by Sonatype, which runs Maven Central. OSSRH is a legacy way of publishing to Maven Central, but Sonatype is modernizing it with a new publisher service. But that service is not fully ready yet, so some projects have not yet been migrated to using it yet (revelc is one that has not been migrated yet). The way you're publishing seems correct for the current OSSRH publishing mechanism. I don't know what the new mechanism will look like yet. It may require a special plugin and credentials to be passed a different way to use that plugin to upload a deploy bundle. It may also require our credentials to be changed so we have accounts on the new system. I'm not sure yet, because we haven't had to migrate yet.

> The credentials are not user / password. Its user which is encrypted as well as token which is encrypted. Even if someone broke my token, they would not have my password and I'm not aware of any way to print out that data given how it is handled. If that were the case, credentials in github shouldn't exist at all. That stuff shows up as *** when printed, I'm not aware of any current defects to break that and I can reject the token at any time if hacked. Do you have a specific case in might where that is currently possible?

While GitHub Actions takes efforts to prevent secrets from being logged to the console, it can be exported and used by others with write access to the repo (me, for instance... if I wanted, I could extract your secret). GitHub frequently warns about this kind of thing. See also https://stackoverflow.com/a/62143130, which says the same thing. I will not, however, be providing a detailed example of how it could be done, because that seems like a bad idea.

However, my main concern here isn't the leakage of your secret... it's nonrepudiation of your personal credentials. You're using your unique credentials to publish SNAPSHOTS, but those snapshots could be triggered by anybody who has permission on the repo, which includes several people, not just me and you. They could also modify the build to use those same credentials to publish a release, instead of a snapshot, using your credentials. That means that through your credentials, the project could have something published that contains something malicious. And that would do harm to the project beyond the mere loss of your credentials.

I do not feel comfortable having your personal publish credentials tied to the build. And, it seems it's only being done to publish snapshots directly from GitHub Actions. And, I just don't see the benefit there... certainly not sufficient benefit to justify the security risks of sharing your credentials and making it possible to publish releases from GitHub Actions using your credentials.

**Comment by hazendaz** [comment]
ok feel free to remove then.  I get what you are saying and that is true if someone has proper access to do so.  Hasn't been a problem elsewhere but I'm fine either way.

**Pull request merged**
