### PR TITLE
Releasing oxygen version

### LINKED ISSUE #255: Update for Eclipse Oxygen
I'm not even sure if the formatter changed at all between Neon and Oxygen... but either way, we should update to the latest jdt-core dependency and formatter, so it's available to users.

### PR DESCRIPTION
**Pull request by hazendaz**
Fixes #255

### CODE REVIEW

**Comment by hazendaz** [comment]
Ignoring appveyor as it failed retrieving maven.

**Comment by ctubbsii** [comment]
Appveyor is likely to break every time upstream Maven releases a new build. The Apache Software Foundation, of which I'm a member, has a release distribution policy of aging out old releases to archives, where the URL has changed and where the archives have bandwidth restrictions, to avoid overloading servers. If we can modify the Appveyor build to not have to download Maven every time, that would be best, so we don't have to modify it every time Maven releases a new version. Unfortunately, I don't know if that's possible. I've created #257 to deal with it this time.

**Comment by hazendaz** [comment]
Thanks!  I presume they might have aged that one quicker as 3.5.0 had some serious bugs.  One of which caused me quite a nightmare this past week with snapshot released being totally hosed due to meta data and file timestamp differences.

**Comment by hazendaz** [comment]
Also, really thank you for taking the time to work on this repo.  The release process is as I'd expect now so great job on fixing the issues that we had with releasing.  Now I think we can really have a go at further improvements.  I'm hoping we start seeing contributors coming in more, that would be great!

**Pull request merged**
