### PR TITLE
Update maven plugins (javadoc / enforcer)

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by ctubbsii** [comment]
@hazendaz I started on a parent POM which might make it easier to manage plugin versions, and common things like formatting, findbugs, etc. in https://github.com/revelc/revelc

If interested, we could move the formatter-maven-plugin over to using that. It might help to offload some of this kind of maintenance. I won't push it, but thought I should mention that it's there, in case there's interest.

**Comment by hazendaz** [comment]
hi @ctubbsii I have one too that I have up-to-date but maybe more than you might want to see here.  I've been somewhat reluctant to bring it into any projects that are more mainstream more for worry of what others might want or not want in a pom as it is big.  Its preconfigured with a ton of stuff.  Maybe you could also take a quick look over [there](https://github.com/hazendaz/base-parent)

**Comment by hazendaz** [comment]
I should note, I pretty much wacked the entire maven super pom with mine.  I use a variation with my day job.  It certainly does offload things significantly.

**Comment by ctubbsii** [comment]
Wow, that's... extensive... I've tried to keep the revelc one a bit more modest, but I've also been neglecting it lately. It may benefit from one or two things you've put in yours. Feel free to do PRs against it if you think it needs anything, whether or not we end up using it for this formatter. One thing I'll say, though, is that I prefer far fewer properties, in favor of more frequent parent POM releases when stuff needs to be updated.

One thing I'll note in yours: you probably don't need both spotbugs and findbugs, since spotbugs should replace findbugs. I did, however, like your use of owasp and findsecbugs plugins, though I'd probably put owasp in a profile, because I think it requires online, and as a downstream packager in Fedora, I like to make offline builds easy on packagers.

**Comment by hazendaz** [comment]
On spotbugs / findbugs....I'm the one building the maven plugin.  It's forked from original.  I've been getting a lot of cleanup back on that one.  My intent here is more for testing as I want to make sure both can work at the same time and produce reports.  I have not yet gotten that far in my varificantions.  Once I get there, findbugs will get removed.

**Comment by hazendaz** [comment]
But yes, overall the super pom is extensive.  It's been a labor of love for 4 years or so.  And really how I learned maven to start with.  I've used it more for a guideline on various projects on github such as mybatis and waffle.

**Pull request merged**
