### PR TITLE
[cleanup] Use java files where possible and reduce guava usage

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by ctubbsii** [comment]
There's a nice tool I use on other projects called modernizer-maven-plugin, which helps catch uses of things that have historically been done using 3rd party libraries, but which are able to be done directly in Java. It also catches when there's a deprecated or not-recommended Java built-in (such as using the built-in APIs for IO that don't specify a Charset when an overloaded method was added to allow Charset to be specified). I don't know if that plugin would have caught these, but it's something worth considering to add to the parent POM.

**Comment by hazendaz** [comment]
I have modernizer and many others on my super parent....https://github.com/hazendaz/base-parent/blob/master/pom.xml

modernizer would not have caught these.  I forget what I used to catch them.  Might have been sonarlint or error prone.  Some scanner indicated to fix but also knew that bulk of guava is in the jvm since java 8 days and more so recently.  plexus stuff I knew only because I follow maven closely and more or less that is all obsolete and best we get out of our builds.  Any plexus stuff that was transitively used is what caused most conflict on getting to maven 3.9.x for plugin providers as maven stopped delivering some of that stuff with maven as it was technically end of life back with maven 2.  So again, some of that I may have found with tools or combination of simply knowing.  Would it be helpful if modernizer knew more about some of that, yes ;)

**Comment by ctubbsii** [comment]
I wouldn't mind adding an errorprone profile in the parent POM at some point, and activating it for an extra GitHub Actions check, but I wouldn't want it to be the default compiler. I've used it before and it catches good things. I don't know about sonarlint, though. I've never used that.

**Comment by hazendaz** [comment]
sonarlint is a plugin for the IDE.  Not sure if there is a maven based plugin for same.  I use error prone on pretty much everything I do.  Its great but it does tend to have issues on newer jdks more often than not so that is the only real downside to it.  So I agree, having it is great under a profile but not really on every build.

**Pull request merged**
