### PR TITLE
Added sort plugin to the mix

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by hazendaz** [comment]
Merging.  However, question about this plugin vs the tidy-maven-plugin which is supported by maven team. Is this one any better?

**Comment by velo** [comment]
I didn't knew this tidy-maven-plugin....  

sortpom seems to be more flexible, it has some configurations, tidy-maven-plugin has no configurations at all (o.0)

**Comment by ctubbsii** [comment]
I've found tidy to be a bit buggy, and inflexible, at least for now.

**Comment by hazendaz** [comment]
Earlier one was.  Much better on the beta copy.  Of course it's still beta...perpetual beta...


Sent by Outlook for Android





On Sun, Aug 9, 2015 at 9:04 PM -0700, "Christopher Tubbs" <notifications@github.com> wrote:
I've found tidy to be a bit buggy, and inflexible, at least for now.

On Sun, Aug 9, 2015, 18:46 Marvin Froeder <notifications@github.com> wrote:

> I didn't knew this tidy-maven-plugin....
>
> sortpom seems to be more flexible, it has some configurations,
> tidy-maven-plugin has no configurations at all (o.0)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/revelc/formatter-maven-plugin/pull/66#issuecomment-129258258>
> .
>


---

**Pull request merged**
