### PR TITLE
added HTML, XML, JSON and CSS formatting

### PR DESCRIPTION
**Pull request by YoshiMan**
added HTML and XML formatting via jsoup https://jsoup.org/
added JSON formatting via gson https://github.com/google/gson
added CSS formatting via CSS Parser http://cssparser.sourceforge.net/

### CODE REVIEW

**Comment by hazendaz** [comment]
Awesome and awesome.  Thank you so much!  Can't wait to try this out

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
@YoshiMan If you can, add in some of the other various format support that are html related.  Possibly jsp, jspx, xhtml, etc.  For now, this is great and very glad to see nice clean commits bringin in each functional piece.  I'm merging this.  Thank you so much!

**Comment by YoshiMan** [comment]
Hey @hazendaz you are welcome :)
We have the problem that the css formating removes comments. I opened a [ticket](https://sourceforge.net/p/cssparser/feature-requests/5/) to keep the comments.

I also tried SQL formatting with hibernates [BasicFormatterImpl.java](https://github.com/hibernate/hibernate-orm/blob/2964ecbf1b74003fcc337b0574487c724638fe94/hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/BasicFormatterImpl.java) and [DDLFormatterImpl.java](https://github.com/hibernate/hibernate-orm/blob/2964ecbf1b74003fcc337b0574487c724638fe94/hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/DDLFormatterImpl.java). But it did not work as i expected.
But i see the problem you want to solve, because pull request with a "dirty" code base is the worst.

**Comment by mcahornsirup** [comment]
Nice work, bro!

**Pull request merged**
