### PR TITLE
Rework logic for end of line processing fixes #531

### LINKED ISSUE #531: fixLineEnding logic is incredibly wrong
When no formatting is determined to have occurred, the code will go into attempting to fixLineEndings for all types including those that did not support it during normal formatting.

If line ending is set to keep, its skipped.

If then tries to figure out line endings presumably because they are mixed.
- If the result is unknown, its skipped.
- If most used matches what was requested, it is skipped (this is wrong if mixed content clearly).
- If line ending is auto and requested/determined match it is skipped (this is again wrong if mixed).

Now regardless of mixed issue or not, if it makes it this far, its again wrong as it uses replace for a specific item(s) in string (no actual end of lines here just markers).  For example, if we determined \n was the type but we want \r\n, it will go replace all \n with \r\n which still leaves considerable mixed content and further now breaks lines horribly wrong as all valid ones get doubled up and output is a mess. (ie mixed means there are \r\n and \n, so changing all \n to \r\n will make new lines and leave content mixed throughout).  I have seen this happen before but never could figure out what was causing it (now I know).

To fix this overall, the case here is that we did not format due to no changes or not supported line ending changes, we simply need to stop trying to guess.  Instead, its rather simple, we just normalize to \n first from \r\n or \r.  Then run the process on it.  That way we are fully normalized and fix this mixup.

This is somewhat easy to see with the html formatter because it has significantly mixed content.  I got jsoup to full working correctly which then exposed this and I have this fixed too now with it further now supporting jsoup for line endings.  Will send a PR tomorrow sometime on this once I have confirmed behaviour with current setup since I'm in between on jsoup setup.  All tests do pass with my changes just need to step back from latest jsoup :)

### PR DESCRIPTION
**Pull request by hazendaz**
fixes #531

### CODE REVIEW

**Comment by hazendaz** [comment]
we may not need to have the if / or tests for these now.  also was not sure on xml as it is indicated set elsewhere but we can control better now.  Basically, the second path is for those types that may not have directly supported to make line endings are also processed.  The first pass in if file is updated will try to process line endings.  I guess I had never seen this because I had only one type in files to any formatting would not have ran into issue the html test file has.  I believe that is why others have seen thsi half work as it was doing a messy check to determine line endings but not actually make a correct determination nor would logic then be right.

**Review by ctubbsii — COMMENTED** [review]
I like the approach to normalize first before replacing.

**Review by ctubbsii — APPROVED** [review]

**Comment by ctubbsii** [comment]
@hazendaz Is this ready for another release, or are there more things you want in 2.17.1?

**Comment by hazendaz** [comment]
Lets get the jsdt-core out so its up to date all the way due to this then I'd say lets cut it.  We may end up with 2.17.2 later when jsoup releases.  They don't have any immediate plan which just leaves us on a bad version for a bit longer there.  I also have 2 other items to have them look at which will resolve all our formatting issues with html so I suspect that to be sometime.

**Comment by ctubbsii** [comment]
> Lets get the jsdt-core out

Do you know if that's ready for a release?

**Comment by hazendaz** [comment]
It is, I actually just pushed it a few minutes ago.  Version 3.0.0. I also renamed my branch to 'main' :)

**Comment by hazendaz** [comment]
I wonder though if we want to pick anything up on the xml formatter while at it.  I don't think we are in any real rush or anything and noticed 3 PRs out there that seem to have some value but may not be complete yet.

**Pull request merged**
