### PR TITLE
[pom] Drop back to marvinformatics 1.7.0

### PR DESCRIPTION
**Pull request by hazendaz**
Drop back to 1.7.0 as 1.8.0 requires jdk8

### CODE REVIEW

**Comment by velo** [comment]
Eclipse neon demands jdk8

**Comment by ctubbsii** [comment]
I'm okay worth bumping to jdk8 also.

**Comment by hazendaz** [comment]
For enterprise usage and a physical mars release, I would like to keep at jdk7.  There are plenty of defects that still need addressed in 'issues' before this can be released at that level otherwise is causes regression from prior 0.5.2 release.  While moving to jdk8 seems fun, enterprise usage is not there yet and probably won't be for another 6 to 12 months.  Most usage is just getting out of jdk 6 earlier this year.  If the prior defects under issues can get addressed, I would want to cut the next release.  That alone will take 4 to 5 months just to get into our system after that.  There are a lot of reasons behind that but in enterprise usage, software must go through external scanning complexes before it's deemed safe for enterprise usage.  I can get checks ahead of time though to confirm that the next release is good before official usage.  So that isn't to say we wait forever for moving to jdk8 but just long enough to get the current one out and confirm we have no defects.  At that point, it wouldn't make much sense to use internally the separate project but make it use the same project for formatting.  Technically we probably should do that now but I've otherwise left it alone.  As far as this upgrade, you can guess I use jdk8 only on my machine so I didn't cause the failure until travis reported it.  I had moved from 1.6.0 to 1.8.0 and just back to 1.7.0 due to this.  I marked versioneye that the full upgrade will be avoided for now.

As far as the defects go, I don't have any time really to address any of them at this time.  We need help there.  At best, I've just been maintaining third party dependencies as of recently only because that takes next to no time and ultimately my tracking of 30+ projects starts growing quickly if I don't stay on top of that.

**Comment by velo** [comment]
Well, whoever it's stuck at java 6 can keep using an obsolete version as well.

**Comment by ctubbsii** [comment]
I agree with @velo. The way I'd prefer to support folks with older JRE requirements (7 and earlier), is to support them on earlier versions of the plugin. Newer versions of the plugin can have stricter requirements. I don't think requiring a non-EOL version of Java is too much to expect for the next version of the plugin released.

**Pull request merged**
