### PR TITLE
Update AbstractCacheableFormatter.java

### PR DESCRIPTION
**Pull request by velo**
Testing build after #80

### CODE REVIEW

**Comment by velo** [comment]
CI says all is good, looks like a good idea to merge this as it is

**Comment by hazendaz** [comment]
Is this correct?  That is the source that was just applied.  The change here is to break the formatting?  GIT only shows exactly what couple of lines the other developer brought in.  It hasn't formatted since.

maven-plugin/src/main/java/net/revelc/code/formatter/AbstractCacheableFormatter.java

**Comment by velo** [comment]
before PR #80 both CI servers would break, saying the format is broken.

**Comment by velo** [comment]
yes, the goal of this PR is to prove PR80 introduced an error to the build.

I completely broke a file format, still the build is green.
So, either the build is wrong or we consider unformatted code a good thing

**Comment by hazendaz** [comment]
that probably is the case because we have to enforce at CI level to enforce.  It's not right now.  all i did was loosen it at the development level.  at travis we will need to modify it slightly so it chokes on that.  Same with appvoyer.  that is true ci in that case.  it can be enforced in any build.  If it helps, I can work that out by end of weekend so we can then keep this PR so we can test it failing again.

**Comment by hazendaz** [comment]
and then developers will still be ok to do what they want but won't be able to submit to use unless clean :)

**Pull request merged**
