### PR TITLE
[ci] Bump version to 2.9.0-snapshot and add notes for ecipse id 2019-…

### PR DESCRIPTION
**Pull request by hazendaz**
…03 to readme

### CODE REVIEW

**Comment by hazendaz** [comment]
@ctubbsii Updated per request on #295 .  However, we have a slight issue on what we termed as photon release as that was really 2018-09.  I'm not sure it matters that much so I didn't touch it here and honesting I didn't at first notice when Eclipse switched over to year/mm format for releases until sometime after the September release.  I'm sure others likely didn't notice that either at first.

**Comment by ctubbsii** [comment]
@hazendaz Hmm. Are you sure?

I think I may somehow have two different installations which are both labeled 2018-12, one with jdt-core 3.16.0 and another with jdt-core 3.17.0. What did photon ship with?

I'm wondering if this version mapping is helpful at all... one release of Eclipse has 3 different version numbers that matter to us, and we're not even documenting the most important one: jdt-core (although that's arguably the one that a user is least likely to be familiar with).

**Comment by hazendaz** [comment]
I didn't find anything definative but looking at releases in central it would appear photon was with 3.14.0 back in June.   

```
org.eclipse.jdt | org.eclipse.jdt.core | 3.17.0 | 16-Mar-2019 | pom  jar  javadoc.jar  sources.jar
org.eclipse.jdt | org.eclipse.jdt.core | 3.16.0 | 19-Dec-2018 | pom  jar  javadoc.jar  sources.jar
org.eclipse.jdt | org.eclipse.jdt.core | 3.15.0 | 25-Sep-2018 | pom  jar  javadoc.jar  sources.jar
org.eclipse.jdt | org.eclipse.jdt.core | 3.14.0 | 14-Jun-2018 | pom  jar  javadoc.jar  sources.jar
```

**Comment by ctubbsii** [comment]
Based on those dates, I'm probably mis-remembering one of my 2018-12 installs having 3.17.0 when it probably only has 3.16.0.

I looked at our tags. It looks like we just skipped over 3.14.0...  which I guess is fine. I probably grabbed 3.15.0 around the time 2018-09 was released, under the assumption it was just a Photon patch. The naming convention switch confused me.

In any case, the README is fixable... if it even matters (I'm not super convinced that the mapping is useful).

**Comment by hazendaz** [comment]
It confused me as well.  I release bundles at work with numerous extras and had called the september release photon at the time ;)  I'm not convinced the mapping matters either.  I don't hear enough concern whem eclipse setup conflicts with the plugin setup and differences for it to really matter much.  Ultimately the maven build wins out in getting committed eventually.  The mapping is probably just more of an informational suggestion as to where we stand with Eclipse.

**Comment by ctubbsii** [comment]
> Ultimately the maven build wins out in getting committed eventually

Exactly.

I do think the mapping would be better on a wiki than in the README, though. At least there, it can be kept up-to-date, regardless of what ships in the README of any particular release.

**Comment by ctubbsii** [comment]
I created https://github.com/revelc/formatter-maven-plugin/wiki/Eclipse-Version-Compatibility to track what we know about recent versions. Prior to that, it was a bit of a mess.

**Pull request merged**
