### PR TITLE
Velo merge

### PR DESCRIPTION
**Pull request by velo**
Wanna check if travis is no able to build this

### CODE REVIEW

**Comment by velo** [comment]
naice!

**Comment by velo** [comment]
So, what is next?
@ctubbsii

**Comment by ctubbsii** [comment]
@hazendaz Thoughts on how next to proceed? Any concerns about this merge? I'm kinda deferring to you, since you've been the most active contributor lately.

**Comment by hazendaz** [comment]
I haven't had much time here lately to really get on github.  I'd like to clean up some of the commit messages such as ones stating svn to git as that is a bit confusing since we are both there.  I can mess with this tonight to cleanup those messages.  Let me get you a better answer once I check this out tonight.  Maybe it's just that concern and everything else is good.  With any luck maybe we can bang this out shortly.


Sent by Outlook for Android





On Mon, Jul 27, 2015 at 10:21 AM -0700, "Christopher Tubbs" <notifications@github.com> wrote:
@hazendaz Thoughts on how next to proceed? Any concerns about this merge? I'm kinda deferring to you, since you've been the most active contributor lately.

---

**Comment by velo** [comment]
nice @hazendaz lemme know how I can assist

**Comment by velo** [comment]
I just noticed the build skip tests...
https://travis-ci.org/revelc/formatter-maven-plugin/jobs/72771365#L96

Should I fix that?

**Comment by hazendaz** [comment]
Here is what I would like to do if it's ok with everyone.  There are currently 99 commits in this.  I've merged this locally on my master then --soft removed the head.  This dropped the file count to 91.  Now I'd like to go through make sure anything out of sync is sync'd up and things come in clean as if this is pretty much brand new work.  So the result will be a significant less amount of commits.  I don't know that we care so much about the year(s) apart as much as we do simply bringing this in and getting a good start.  By going this route, it will be easier to follow.  If everyone is ok, I'll try to get this completed by end of this coming weekend so we can start out next week on a very strong footing.

**Comment by velo** [comment]
Well, either way is fine with me.... more commits, less commits, I don't really se any point of going to more or to less.

What I really would like to see if a release with mars... my code is all set for it, but I prefer the next release to be one joining the fork back

**Comment by hazendaz** [comment]
Sounds good.  I'll work on it.  Mainly I just want to get my head wrapped around all your work.  It's definitely a good direction with this project.

**Comment by velo** [comment]
Some outlines them....
https://github.com/revelc/formatter-maven-plugin/tree/velo-merge/formatters
It contains a maven project that downloads jdt (and jsdt) from eclipse p2 repositories and build a jar from it.  That makes this project independent to pump jdt version at will.
In theory we could go eclipse 4.6 right now!

https://github.com/revelc/formatter-maven-plugin/tree/velo-merge/m2e-configurator
m2e configurator, so eclipse would use same configurations maven would.
eclipse plugin

https://github.com/revelc/formatter-maven-plugin/tree/velo-merge/maven-plugin
the maven plugin itself.  Equivalent to current top level

**Comment by hazendaz** [comment]
So I grabbed this as-is and just did a merge --no-ff onto master and attempted a build.  It doesn't pass unit tests.  Can you take a quick look at why?  I'm using jdk8 update 51 for reference.

Failed tests:   testAsInputStreamValidDefaultPackageResource(net.revelc.code.formatter.support.io.ResourceTest): expecte
d:<alpha[]
  testForPath(net.revelc.code.formatter.support.io.ResourceTest): expected:<alpha[]
  testAsString(net.revelc.code.formatter.support.io.ResourceTest): expected:<alpha subpackage[]
  testAsInputStreamValidSubpackageResource(net.revelc.code.formatter.support.io.ResourceTest): expected:<alpha subpackag
e[]
  testLoadInputStreamClasspath(net.revelc.code.formatter.support.io.ResourceTest): expected:<alpha subpackage[]
  testLoadInputStreamFile(net.revelc.code.formatter.support.io.ResourceTest): expected:<alpha[]

Tests run: 17, Failures: 6, Errors: 0, Skipped: 0

**Comment by hazendaz** [comment]
Here is an update of where I'm at.

I've started to align this project with @velo layout and the package naming changes made there.  So this will start with new package naming and I think we need to bump to 2.0.0 for this.  For the remainder, it's definitely like a large replacement (err...rewrite).  So if @ctubbsii and @mblanchette can additionally jump in and run some tests using the current @velo version in central just for verification purposes, that would be great.  I plan to run this on a few 100K lines of code to see what shakes out over the next few days using the RC4.  

'<dependency>
    <groupId>com.marvinformatics.formatter</groupId>
    <artifactId>formatter-maven-plugin</artifactId>
    <version>1.6.0.RC4</version>
</dependency>'

In the next couple of days, I will get a new PR that will commit each folder under a separate commit.  This will help a bit as the histories don't match and were going to long in different directions.  The core piece here is seeing what actually changed in the code line from this to @velo.  We probably will have a bit of cleanup work in poms potentially when it's done but hopefully no regression.  I've seen some areas still mentioning 'google.code' which were cleaned up here so I suspect we will need to look carefully once this comes in officially.

**Comment by velo** [comment]
@hazendaz 
All tests passed to me =/
````
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:35 min
````

**Comment by hazendaz** [comment]
Ya possibly.  I got on a roll and mostly got the basics completed now.  It was complaining of no version for proguard as I have enforcer rules.  So put in the latest as that is what I believe it would be using anywase.  Not 100% sure.  Now I get this.  Any ideas?  I'll push up my PR in a few minutes as a reference.

 [proguard] ProGuard, version 5.2
 [proguard] Reading program jar [C:\Users\Jeremy\Documents\GitHub\formatter-maven-plugin\formatters\jdt-core\target\jdt-
core-1.6.0-SNAPSHOT.jar] (filtered)
 [proguard] Error: The input doesn't contain any classes. Did you specify the proper '-injars' options?

**Comment by velo** [comment]
how can I run it here with this enforcer rules?

FWIW, here is running with 2.0.10
````
[INFO] --- proguard-maven-plugin:2.0.10:proguard (default) @ jdt-core ---
````

**Comment by hazendaz** [comment]
I give up for tonight.  The eclipse jars were downloaded but don’t contain any classes.  That is the issue.  Not sure why that is occurring.  Will look again tomorrow.  Probably just missing something simple on that or maybe those got changed since it grabs snapshots.  Tomorrow I will try again on your branch and see what happens.

 

Jeremy

**Comment by hazendaz** [comment]
I want to start out fresh here.  When I first looked at this, I think the commit history is what scared me so I wanted to clean it up so it was on top of ours.  So lets take one of two routes and call this done.

Options
1) We just merge a single commit in stating it is coming from @velo 
2) We don't care that the history will not look quite right and just merge this.

I favor option 1 only in so much that we all know this is the new future and after really looking it's all there.  Alternative merge is coming but I'd prefer to get @velo name on it if we pick option 1.

**Comment by velo** [comment]
I prefer 2) cause sometimes history helps to find out why something got broken.

Like yesterday, the proguard was broken... I had no idea what was broken, but when I looked at this commit where proguard was introduced, it became quite obvious to me

**Comment by hazendaz** [comment]
Point taken.  I'm changing my vote to #2.  Expect this to be merged by tomorrow so we can start real work.


Quick question.  I tried to run rc4 on my code which uses a jar file with formatter xml.  I got an error that it could not find it.  This works fine with current code.  Any ideas?  I would like a quick test on a very large library.  I can move my configuration for now to test...


Sent by Outlook for Android





On Thu, Jul 30, 2015 at 9:58 PM -0700, "Marvin Froeder" <notifications@github.com> wrote:
I prefer 2) cause sometimes history helps to find out why something got broken.

Like yesterday, the proguard was broken... I had no idea what was broken, but when I looked at this commit where proguard was introduced, it became quite obvious to me

---

**Comment by velo** [comment]
If that is something new (new meaning post SVN) it may be not implemented on my side...

**Comment by ctubbsii** [comment]
I also prefer option 2, so long as it's merged with "--no-ff", so we can easily see the history down the side branch and see where it was merged in (this is the default from the web interface).

**Comment by hazendaz** [comment]
#2 it is.  As soon as this is merged we will need to start digging deep to see anything we lost as a result.  I've got some fixes on my branch to get over.  I suspect some site generation issues and poms for the most part.  I believe its missing ability to read from a jar but should be easy to discover that.  We should also review all recent commits for any regressions.  It will be while this morning before I can get to this so feel free to merge away.


Sent by Outlook for Android





On Fri, Jul 31, 2015 at 4:03 PM -0700, "Christopher Tubbs" <notifications@github.com> wrote:
I also prefer option 2, so long as it's merged with "--no-ff", so we can easily see the history down the side branch and see where it was merged in (this is the default from the web interface).

---

**Comment by hazendaz** [comment]
Lets do this too.  Save off our original as a branch for at least short term.  I'm extra paranoid...lol


Sent by Outlook for Android





On Sat, Aug 1, 2015 at 7:09 AM -0700, <jeremylandis@hotmail.com> wrote:
#2 it is.  As soon as this is merged we will need to start digging deep to see anything we lost as a result.  I've got some fixes on my branch to get over.  I suspect some site generation issues and poms for the most part.  I believe its missing ability to read from a jar but should be easy to discover that.  We should also review all recent commits for any regressions.  It will be while this morning before I can get to this so feel free to merge away.


Sent by Outlook for Android





On Fri, Jul 31, 2015 at 4:03 PM -0700, "Christopher Tubbs" <notifications@github.com> wrote:
I also prefer option 2, so long as it's merged with "--no-ff", so we can easily see the history down the side branch and see where it was merged in (this is the default from the web interface).

---

**Comment by hazendaz** [comment]
I made a backup of the master branch.  There are some issues as I have already noted so since we already have the velo-merge branch, lets work there until it looks like we got everything.  First issue, the new version regressioned on reading from jar file for configuration.  I found the issue and I'm patching that now.  We probably should close this PR for now, work the merge-velo branch and when complete get that merged to master. 

Thoughts?

**Comment by velo** [comment]
Agreed

**Comment by velo** [comment]
So, lets merge this and cut our first RC?

**Comment by velo** [comment]
I will flip the switch.... if needed it can be undone.

**Comment by hazendaz** [comment]
Sounds great!  I just recently upgraded at work to the last release and did so on most third parties I work on so this stage will work out well as it should now be much easier to test on live code.  I still need to switch to Google style then will dive more into this.  If you feel ready for release candidates feel free to push them.  Thanks for all your hard work.


Sent by Outlook for Android





On Wed, Sep 2, 2015 at 4:13 PM -0700, "Marvin Froeder" <notifications@github.com> wrote:
I will flip the switch.... if needed it can be undone.

---

**Pull request merged**
