### PR TITLE
Fix caching of already formatted files

### PR DESCRIPTION
**Pull request by fralalonde**
Fix for #312

### CODE REVIEW

**Comment by fralalonde** [comment]
This restores performance:
```
[INFO] Number of files to be formatted: 2918
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         2918 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          1s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.942 s
```

**Comment by ctubbsii** [comment]
See my comment on #312

**Comment by fralalonde** [comment]
See my answer on #312

**Comment by hazendaz** [comment]
@fralalonde Can you try PR #367 and see if that also resolves your issue?

**Comment by hazendaz** [comment]
This has been fixed in a better way that solves this issue.  This would have regressed other portions of code.

**Pull request closed without merging**
