### PR TITLE
Revelc

### PR DESCRIPTION
**Pull request by velo**
So, I created a PR to merge my fork back to this project!

Someone wouuld need to review (specially the poms) to make sure I do not killed something.

I renamed all packages and groupIds to net.revelec.code

Cheers

### CODE REVIEW

**Comment by velo** [comment]
````
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

The build has been terminated.
````

Any chance to move to shippable? My build works like a charm there....
https://app.shippable.com/builds/55ac65c36507280b00fb072e

**Comment by hazendaz** [comment]
I've got an idea that might this easier to pull in.  At the moment we are both highly diverted over at least a year while a lot is still common.  If I create a branch and you do a PR there, I'll merge.  Then I'll attempt what I assume will be a fun 'rebase'.  This way duplicate commits and or unnessary ones can be removed.  All your changes will float on top.


One other thing I'd like to check out after this.  I read m2e connectors are no longer needed.  The plugins can be self registered now.  Maybe we can have both for legacy users.


Thoughts?


Sent by Outlook for Android





On Mon, Jul 20, 2015 at 1:35 AM -0700, "Marvin Froeder" <notifications@github.com> wrote:
So, I created a PR to merge my fork back to this project!

Someone wouuld need to review (specially the poms) to make sure I do not killed something.

I renamed all packages and groupIds to net.revelec.code

Cheers
You can view, comment on, or merge this pull request online at:

  https://github.com/revelc/formatter-maven-plugin/pull/53

-- Commit Summary --

  * Convert svn:ignore properties to .gitignore.
  * Make room for other languages then java
  * Pom personal touch
  * No real use for guava
  * Created JS formatter
  * Code format
  * Enable JS format
  * Changed project structure to consume formatter artifacts from P2 repository
  * Bumped to eclipse juno formatter
  * Rearanged packages
  * Using java 5 annotations
  * Fix lineendings if format is ok
  * Add validate goal
  * [maven-release-plugin] prepare release formatter-1.0.0
  * mode changes
  * [maven-release-plugin] prepare for next development iteration
  * hate file modes
  * Next development version
  * Add expression for includes
  * Fixed lineendings
  * [maven-release-plugin] prepare release formatter-1.1.0
  * [maven-release-plugin] prepare for next development iteration
  * Next development version
  * First very rudimentar attempt to create a m2e configurator
  * Now using osgi preferences service
  * Added samples
  * Add aggregator configurator for validation
  * Fixed feature name and description
  * Fixed catalog.xml
  * [release] next stable version
  * Added release stuff
  * Catalog
  * [release] next development version
  * Create README.md
  * Making room for more formatters
  * Added kepler repository
  * Preparing next release
  * Fix parent name
  * Preparing next development version
  * Update README.md
  * Bump eclipse version
  * [Release 1.4.0.M6 matching luna M6]
  * Next development version
  * Added java 8 support
  * 1.4.0 released
  * Ignoring pom.xml.versionsBackup
  * Next dev version
  * PlexusIoFileResourceCollection is trying to touch all files, ignoring exclusion rules, dont wanna play nice? ok, you are gone.
  * 1.4.1 release
  * Next release development
  * Enhancement to add support for classpath sources formatter
  * Add plugin to shippable!
  * Update README.md
  * Removed duplicate developers section, per project owner feedback.
  * Update README.md
  * Added maven central badge
  * Update .shippable.yml
  * Update .shippable.yml
  * 1.5.0
  * 1.6.0 development
  * Fixed compilation after rebasing
  * Merge pull request #1 from velo/mblanchette_rebased
  * Update README.md
  * Update README.md
  * Coveralls
  * Jacoco workarounds!
  * typo
  * Fixing global.env
  * Create .rultor.yml
  * Merge remote branch 'fork/improvements'
  * Update README.md
  * Added issues, forks and stars
  * Added license
  * Preparing for eclipse mars
  * Merge remote-tracking branch 'revelec/master' into align
  * 1.6.0.RC1
  * Next development version
  * Update README.md
  * Merge pull request #4 from velo/align
  * Generating p2 update site
  * Preparing rultor release
  * Testing rultor release
  * Testing rultor release
  * Update pom.xml
  * Testing rultor release
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Shrinking all eclipse jar
  * Merge remote-tracking branch 'fork/shrink'
  * Merge remote-tracking branch 'revelec/master'
  * Rebranding to revelc

-- File Changes --

    M .gitignore (187)
    A .rultor.yml (13)
    A .rultor/pubring.gpg.asc (63)
    A .rultor/secring.gpg.asc (120)
    A .rultor/settings.xml.asc (23)
    A .shippable.yml (18)
    M README.md (49)
    A formatters/jdt-core/META-INF/MANIFEST.MF (7)
    A formatters/jdt-core/build.properties (4)
    A formatters/jdt-core/pom.xml (14)
    A formatters/jdt-core/proguard.conf (12)
    A formatters/jsdt-core/META-INF/MANIFEST.MF (7)
    A formatters/jsdt-core/build.properties (4)
    A formatters/jsdt-core/pom.xml (14)
    A formatters/jsdt-core/proguard.conf (11)
    A formatters/pom.xml (62)
    A m2e-configurator/.gitignore (6)
    A m2e-configurator/catalog.xml (25)
    A m2e-configurator/links.txt (4)
    A m2e-configurator/net.revelc.code.formatter.feature/build.properties (3)
    A m2e-configurator/net.revelc.code.formatter.feature/feature.properties (262)
    A m2e-configurator/net.revelc.code.formatter.feature/feature.xml (27)
    A m2e-configurator/net.revelc.code.formatter.feature/license.html (261)
    A m2e-configurator/net.revelc.code.formatter.feature/pom.xml (14)
    A m2e-configurator/net.revelc.code.formatter.site/category.xml (7)
    A m2e-configurator/net.revelc.code.formatter.site/pom.xml (20)
    A m2e-configurator/net.revelc.code.formatter.tests/META-INF/MANIFEST.MF (14)
    A m2e-configurator/net.revelc.code.formatter.tests/build.properties (4)
    A m2e-configurator/net.revelc.code.formatter.tests/plugin_customization.ini (4)
    A m2e-configurator/net.revelc.code.formatter.tests/pom.xml (15)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/modular-sample/modular-sample-child/pom.xml (9)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/modular-sample/pom.xml (27)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/modular-sample/src/config/eclipse/formatter/java.xml (291)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/modular-sample/src/config/eclipse/formatter/javascript.xml (267)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/simple-sample/pom.xml (23)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/simple-sample/src/config/eclipse/formatter/java.xml (291)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/simple-sample/src/config/eclipse/formatter/javascript.xml (267)
    A m2e-configurator/net.revelc.code.formatter.tests/settings.xml (29)
    A m2e-configurator/net.revelc.code.formatter.tests/src/org/sonatype/m2e/buildhelper/tests/BuildhelperTest.java (90)
    A m2e-configurator/net.revelc.code.formatter/META-INF/MANIFEST.MF (15)
    A m2e-configurator/net.revelc.code.formatter/build.properties (6)
    A m2e-configurator/net.revelc.code.formatter/lifecycle-mapping-metadata.xml (20)
    A m2e-configurator/net.revelc.code.formatter/plugin.xml (15)
    A m2e-configurator/net.revelc.code.formatter/pom.xml (15)
    A m2e-configurator/net.revelc.code.formatter/src/net/revelc/code/formatter/connector/FormatterCore.java (22)
    A m2e-configurator/net.revelc.code.formatter/src/net/revelc/code/formatter/connector/internal/FormatterProjectConfigurator.java (198)
    A m2e-configurator/pom.xml (32)
    A maven-plugin/pom.xml (99)
    A maven-plugin/src/main/java/net/revelc/code/formatter/AbstractCacheableFormatter.java (96)
    A maven-plugin/src/main/java/net/revelc/code/formatter/ConfigurationSource.java (41)
    A maven-plugin/src/main/java/net/revelc/code/formatter/Formatter.java (56)
    R maven-plugin/src/main/java/net/revelc/code/formatter/FormatterMojo.java (404)
    A maven-plugin/src/main/java/net/revelc/code/formatter/LineEnding.java (76)
    A maven-plugin/src/main/java/net/revelc/code/formatter/Result.java (24)
    A maven-plugin/src/main/java/net/revelc/code/formatter/ValidateMojo.java (69)
    A maven-plugin/src/main/java/net/revelc/code/formatter/java/JavaFormatter.java (76)
    A maven-plugin/src/main/java/net/revelc/code/formatter/javascript/JavascriptFormatter.java (68)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/ConfigReadException.java (2)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/ConfigReader.java (7)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/Profile.java (2)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/Profiles.java (2)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/RuleSet.java (10)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/Setting.java (2)
    R maven-plugin/src/site/apt/examples.apt.vm (16)
    R maven-plugin/src/site/apt/index.apt.vm (0)
    R maven-plugin/src/site/apt/usage.apt.vm (0)
    R maven-plugin/src/site/site.xml (0)
    A maven-plugin/src/test/java/net/revelc/code/formatter/AbstractFormatterTest.java (90)
    A maven-plugin/src/test/java/net/revelc/code/formatter/LineEndingTest.java (114)
    A maven-plugin/src/test/java/net/revelc/code/formatter/java/JavaFormatterTest.java (32)
    A maven-plugin/src/test/java/net/revelc/code/formatter/javascript/JavascriptFormatterTest.java (29)
    R maven-plugin/src/test/java/net/revelc/code/formatter/model/ConfigReaderTest.java (10)
    A maven-plugin/src/test/resources/AnyClass.java (31)
    A maven-plugin/src/test/resources/AnyJS.js (25)
    R maven-plugin/src/test/resources/sample-config.xml (0)
    R maven-plugin/src/test/resources/sample-invalid-config.xml (0)
    R maven-plugin/src/test/resources/sample-invalid-config2.xml (0)
    M pom.xml (835)
    D src/test/java/com/relativitas/maven/plugins/formatter/FormatterMojoTest.java (108)
    A support/pom.xml (24)
    A support/src/main/java/net/revelc/code/formatter/support/io/Resource.java (221)
    A support/src/main/java/net/revelc/code/formatter/support/text/Template.java (66)
    A support/src/site/apt/examples.apt.vm (264)
    A support/src/site/apt/index.apt.vm (22)
    A support/src/site/apt/usage.apt.vm (71)
    A support/src/site/site.xml (19)
    A support/src/test/java/net/revelc/code/formatter/support/io/ResourceTest.java (235)
    A support/src/test/java/net/revelc/code/formatter/support/text/TemplateTest.java (75)
    A support/src/test/resources/net/revelc/code/formatter/support/io/other_test_file (2)
    A support/src/test/resources/test_file (2)

-- Patch Links --

https://github.com/revelc/formatter-maven-plugin/pull/53.patch
https://github.com/revelc/formatter-maven-plugin/pull/53.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/revelc/formatter-maven-plugin/pull/53

**Comment by hazendaz** [comment]
Maybe you already rebased.  I notice dates only go back a few months now.  If so just confirm...I can review maven stuff.  Only thing that concerns me is svn noted commits...but if rebased already it is what it is ;)


Sent by Outlook for Android





On Mon, Jul 20, 2015 at 1:35 AM -0700, "Marvin Froeder" <notifications@github.com> wrote:
So, I created a PR to merge my fork back to this project!

Someone wouuld need to review (specially the poms) to make sure I do not killed something.

I renamed all packages and groupIds to net.revelec.code

Cheers
You can view, comment on, or merge this pull request online at:

  https://github.com/revelc/formatter-maven-plugin/pull/53

-- Commit Summary --

  * Convert svn:ignore properties to .gitignore.
  * Make room for other languages then java
  * Pom personal touch
  * No real use for guava
  * Created JS formatter
  * Code format
  * Enable JS format
  * Changed project structure to consume formatter artifacts from P2 repository
  * Bumped to eclipse juno formatter
  * Rearanged packages
  * Using java 5 annotations
  * Fix lineendings if format is ok
  * Add validate goal
  * [maven-release-plugin] prepare release formatter-1.0.0
  * mode changes
  * [maven-release-plugin] prepare for next development iteration
  * hate file modes
  * Next development version
  * Add expression for includes
  * Fixed lineendings
  * [maven-release-plugin] prepare release formatter-1.1.0
  * [maven-release-plugin] prepare for next development iteration
  * Next development version
  * First very rudimentar attempt to create a m2e configurator
  * Now using osgi preferences service
  * Added samples
  * Add aggregator configurator for validation
  * Fixed feature name and description
  * Fixed catalog.xml
  * [release] next stable version
  * Added release stuff
  * Catalog
  * [release] next development version
  * Create README.md
  * Making room for more formatters
  * Added kepler repository
  * Preparing next release
  * Fix parent name
  * Preparing next development version
  * Update README.md
  * Bump eclipse version
  * [Release 1.4.0.M6 matching luna M6]
  * Next development version
  * Added java 8 support
  * 1.4.0 released
  * Ignoring pom.xml.versionsBackup
  * Next dev version
  * PlexusIoFileResourceCollection is trying to touch all files, ignoring exclusion rules, dont wanna play nice? ok, you are gone.
  * 1.4.1 release
  * Next release development
  * Enhancement to add support for classpath sources formatter
  * Add plugin to shippable!
  * Update README.md
  * Removed duplicate developers section, per project owner feedback.
  * Update README.md
  * Added maven central badge
  * Update .shippable.yml
  * Update .shippable.yml
  * 1.5.0
  * 1.6.0 development
  * Fixed compilation after rebasing
  * Merge pull request #1 from velo/mblanchette_rebased
  * Update README.md
  * Update README.md
  * Coveralls
  * Jacoco workarounds!
  * typo
  * Fixing global.env
  * Create .rultor.yml
  * Merge remote branch 'fork/improvements'
  * Update README.md
  * Added issues, forks and stars
  * Added license
  * Preparing for eclipse mars
  * Merge remote-tracking branch 'revelec/master' into align
  * 1.6.0.RC1
  * Next development version
  * Update README.md
  * Merge pull request #4 from velo/align
  * Generating p2 update site
  * Preparing rultor release
  * Testing rultor release
  * Testing rultor release
  * Update pom.xml
  * Testing rultor release
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Update .rultor.yml
  * Shrinking all eclipse jar
  * Merge remote-tracking branch 'fork/shrink'
  * Merge remote-tracking branch 'revelec/master'
  * Rebranding to revelc

-- File Changes --

    M .gitignore (187)
    A .rultor.yml (13)
    A .rultor/pubring.gpg.asc (63)
    A .rultor/secring.gpg.asc (120)
    A .rultor/settings.xml.asc (23)
    A .shippable.yml (18)
    M README.md (49)
    A formatters/jdt-core/META-INF/MANIFEST.MF (7)
    A formatters/jdt-core/build.properties (4)
    A formatters/jdt-core/pom.xml (14)
    A formatters/jdt-core/proguard.conf (12)
    A formatters/jsdt-core/META-INF/MANIFEST.MF (7)
    A formatters/jsdt-core/build.properties (4)
    A formatters/jsdt-core/pom.xml (14)
    A formatters/jsdt-core/proguard.conf (11)
    A formatters/pom.xml (62)
    A m2e-configurator/.gitignore (6)
    A m2e-configurator/catalog.xml (25)
    A m2e-configurator/links.txt (4)
    A m2e-configurator/net.revelc.code.formatter.feature/build.properties (3)
    A m2e-configurator/net.revelc.code.formatter.feature/feature.properties (262)
    A m2e-configurator/net.revelc.code.formatter.feature/feature.xml (27)
    A m2e-configurator/net.revelc.code.formatter.feature/license.html (261)
    A m2e-configurator/net.revelc.code.formatter.feature/pom.xml (14)
    A m2e-configurator/net.revelc.code.formatter.site/category.xml (7)
    A m2e-configurator/net.revelc.code.formatter.site/pom.xml (20)
    A m2e-configurator/net.revelc.code.formatter.tests/META-INF/MANIFEST.MF (14)
    A m2e-configurator/net.revelc.code.formatter.tests/build.properties (4)
    A m2e-configurator/net.revelc.code.formatter.tests/plugin_customization.ini (4)
    A m2e-configurator/net.revelc.code.formatter.tests/pom.xml (15)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/modular-sample/modular-sample-child/pom.xml (9)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/modular-sample/pom.xml (27)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/modular-sample/src/config/eclipse/formatter/java.xml (291)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/modular-sample/src/config/eclipse/formatter/javascript.xml (267)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/simple-sample/pom.xml (23)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/simple-sample/src/config/eclipse/formatter/java.xml (291)
    A m2e-configurator/net.revelc.code.formatter.tests/projects/simple-sample/src/config/eclipse/formatter/javascript.xml (267)
    A m2e-configurator/net.revelc.code.formatter.tests/settings.xml (29)
    A m2e-configurator/net.revelc.code.formatter.tests/src/org/sonatype/m2e/buildhelper/tests/BuildhelperTest.java (90)
    A m2e-configurator/net.revelc.code.formatter/META-INF/MANIFEST.MF (15)
    A m2e-configurator/net.revelc.code.formatter/build.properties (6)
    A m2e-configurator/net.revelc.code.formatter/lifecycle-mapping-metadata.xml (20)
    A m2e-configurator/net.revelc.code.formatter/plugin.xml (15)
    A m2e-configurator/net.revelc.code.formatter/pom.xml (15)
    A m2e-configurator/net.revelc.code.formatter/src/net/revelc/code/formatter/connector/FormatterCore.java (22)
    A m2e-configurator/net.revelc.code.formatter/src/net/revelc/code/formatter/connector/internal/FormatterProjectConfigurator.java (198)
    A m2e-configurator/pom.xml (32)
    A maven-plugin/pom.xml (99)
    A maven-plugin/src/main/java/net/revelc/code/formatter/AbstractCacheableFormatter.java (96)
    A maven-plugin/src/main/java/net/revelc/code/formatter/ConfigurationSource.java (41)
    A maven-plugin/src/main/java/net/revelc/code/formatter/Formatter.java (56)
    R maven-plugin/src/main/java/net/revelc/code/formatter/FormatterMojo.java (404)
    A maven-plugin/src/main/java/net/revelc/code/formatter/LineEnding.java (76)
    A maven-plugin/src/main/java/net/revelc/code/formatter/Result.java (24)
    A maven-plugin/src/main/java/net/revelc/code/formatter/ValidateMojo.java (69)
    A maven-plugin/src/main/java/net/revelc/code/formatter/java/JavaFormatter.java (76)
    A maven-plugin/src/main/java/net/revelc/code/formatter/javascript/JavascriptFormatter.java (68)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/ConfigReadException.java (2)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/ConfigReader.java (7)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/Profile.java (2)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/Profiles.java (2)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/RuleSet.java (10)
    R maven-plugin/src/main/java/net/revelc/code/formatter/model/Setting.java (2)
    R maven-plugin/src/site/apt/examples.apt.vm (16)
    R maven-plugin/src/site/apt/index.apt.vm (0)
    R maven-plugin/src/site/apt/usage.apt.vm (0)
    R maven-plugin/src/site/site.xml (0)
    A maven-plugin/src/test/java/net/revelc/code/formatter/AbstractFormatterTest.java (90)
    A maven-plugin/src/test/java/net/revelc/code/formatter/LineEndingTest.java (114)
    A maven-plugin/src/test/java/net/revelc/code/formatter/java/JavaFormatterTest.java (32)
    A maven-plugin/src/test/java/net/revelc/code/formatter/javascript/JavascriptFormatterTest.java (29)
    R maven-plugin/src/test/java/net/revelc/code/formatter/model/ConfigReaderTest.java (10)
    A maven-plugin/src/test/resources/AnyClass.java (31)
    A maven-plugin/src/test/resources/AnyJS.js (25)
    R maven-plugin/src/test/resources/sample-config.xml (0)
    R maven-plugin/src/test/resources/sample-invalid-config.xml (0)
    R maven-plugin/src/test/resources/sample-invalid-config2.xml (0)
    M pom.xml (835)
    D src/test/java/com/relativitas/maven/plugins/formatter/FormatterMojoTest.java (108)
    A support/pom.xml (24)
    A support/src/main/java/net/revelc/code/formatter/support/io/Resource.java (221)
    A support/src/main/java/net/revelc/code/formatter/support/text/Template.java (66)
    A support/src/site/apt/examples.apt.vm (264)
    A support/src/site/apt/index.apt.vm (22)
    A support/src/site/apt/usage.apt.vm (71)
    A support/src/site/site.xml (19)
    A support/src/test/java/net/revelc/code/formatter/support/io/ResourceTest.java (235)
    A support/src/test/java/net/revelc/code/formatter/support/text/TemplateTest.java (75)
    A support/src/test/resources/net/revelc/code/formatter/support/io/other_test_file (2)
    A support/src/test/resources/test_file (2)

-- Patch Links --

https://github.com/revelc/formatter-maven-plugin/pull/53.patch
https://github.com/revelc/formatter-maven-plugin/pull/53.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/revelc/formatter-maven-plugin/pull/53

**Comment by ctubbsii** [comment]
I merged this PR into a branch called 'velo-merge'. I'll leave the review and incremental/selective merging to master up to you guys, though if I get a chance, I might jump in and help with the review.

**Comment by velo** [comment]
@hazendaz yes, I already rebased it....

originally, my fork was an independent project that I cloned from code.google svn....

When the source showed up on github, I killed mine, forked the github project and the re applied all my changes (git cherry-pick FTW)


@ctubbsii no problem, we just need to get it merged back to master before master start diverging...

**Pull request closed without merging**
