### PR TITLE
Jautodoc all javadocs which corrected bad ones and remove hacks to ignore javadocs

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by ctubbsii** [comment]
@hazendaz I would disagree that the POM settings, `all,-missing` is a "hack". I actually think it's the preferred approach. This allows us to choose when to add javadocs (when they have value) and when not to add them (when they don't have value). Here's an example that you made in this PR that I would consider mere noise, and not actually valuable javadoc:

```java
    /**
     * Fix line ending.
     *
     * @param code
     *            the code
     * @param ending
     *            the ending
     * 
     * @return the string
     */
    private static String fixLineEnding(String code, LineEnding ending) {
```

As you can see, this javadoc adds nothing to the javadoc that would have been automatically generated, and it forces us to fill in javadocs with noise even when it is meaningless to do so. I would prefer a more targeted approach, adding javadocs where they have value, and leaving the noise out when they don't. As such, I would strongly prefer reverting this patch. What do you think?

**Comment by hazendaz** [comment]
@ctubbsii Yes but not having that provides no javadoc at all.  Having it does show a javadoc.  It may not be very filled out but that can come in time.  I would highly prefer not reverting it.  Its helpful at very least to know what it is besides a big empty nothing when we hover over it.  My firm already requires us do this regardless.  We should fill them out but I stand by my statement ignoring javadoc problems which were a lot (ie not filled in properly but had javadocs) is abuse of javadocs functionality.  Its either don't write them at all or write them correctly.  The plugin jautodoc cannot selectively decide what to do reallly other than just make sure it has something.  And honestly there are barely any in this project.  So we should task to write them out in full in all cases. Its the to having to hop classes when developing this too.  This is a very contentious issue, I fully understand.

**Comment by hazendaz** [comment]
missed adding milestones, if you got them all cool. If not I will circle back in a few.

**Comment by ctubbsii** [comment]
I wasn't saying they didn't have value because they weren't filled out. I was saying that there isn't anything that could conceivably be filled out that would have added anything of value. In some cases, the javadoc is just pure noise... making the file bigger and longer to scroll, more to skip past, and not actually worth reading. It would be better in many cases to have none at all. Also, you ended up removing the doclint entirely. You didn't just remove the `-missing`, but you removed the `all` as well. I don't think the default is to be as strict as `all` is.

**Comment by hazendaz** [comment]
javadocs are strict by default since java 8.  warnings won't fail but anything missing will cause failure.

**Comment by hazendaz** [comment]
errors too of course which sometimes are hard to spot.

**Comment by ctubbsii** [comment]
> javadocs are strict by default since java 8. warnings won't fail but anything missing will cause failure.

Okay, well, missing javadocs shouldn't fail. It's dumb to require them by default. The other warnings are good, though. That's why `all,-missing` was just fine.

**Pull request merged**
